name: Build iOS Unsigned IPA

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build unsigned IPA
        run: |
          set -e

          echo "Current dir:"
          pwd
          echo "Files:"
          ls -lah

          PROJECT_DIR=$(dirname "$(find "$GITHUB_WORKSPACE" -name pubspec.yaml | head -n 1)")
          echo "PROJECT_DIR=$PROJECT_DIR"

          cd "$PROJECT_DIR"

          flutter pub get
          flutter build ios --release --no-codesign

          mkdir -p build/ios/ipa/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -qry unsigned.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: "**/build/ios/ipa/unsigned.ipa"
